export const mockData = {
  quickStats: [
    {
      title: "Faculty Members",
      value: 24,
      icon: "User",
      trend: "+2 this semester",
      trendUp: true,
    },
    {
      title: "Total Students",
      value: 450,
      icon: "Users",
      trend: "+45 from last year",
      trendUp: true,
    },
    {
      title: "Active Courses",
      value: 3,
      icon: "Book",
      trend: "All running",
      trendUp: true,
    },
    {
      title: "Upcoming Exams",
      value: 2,
      icon: "Calendar",
      trend: "Next in 3 days",
      trendUp: false,
    },
  ],
  upcomingExams: [
    {
      id: 1,
      subject: "Data Structures",
      type: "CAT-1",
      date: "2025-02-15",
      status: "Ready",
    },
    {
      id: 2,
      subject: "Database Management",
      type: "Final",
      date: "2025-02-20",
      status: "Pending Review",
    },
  ],
  subjects: [
    {
      id: 1,
      name: "Data Structures",
      semester: 3,
      faculty: "Dr. Smith",
      progress: 75,
    },
    {
      id: 2,
      name: "Database Management",
      semester: 4,
      faculty: "Prof. Brown",
      progress: 60,
    },
    {
      id: 3,
      name: "Machine Learning",
      semester: 7,
      faculty: "Dr. Williams",
      progress: 45,
    },
  ],
  recentActivities: [
    {
      text: "New exam paper submitted for Data Structures",
      desc: "CAT-1 examination",
      time: "2 hours ago",
      icon: "FileUp",
      color: "blue",
    },
    {
      text: "Faculty meeting scheduled",
      desc: "Department review",
      time: "5 hours ago",
      icon: "Users",
      color: "green",
    },
    {
      text: "Exam schedule updated",
      desc: "Final examinations",
      time: "1 day ago",
      icon: "Calendar",
      color: "purple",
    },
  ],
  analyticsSummary: [
    { label: "Average Attendance", value: "87%", trend: "+2.5%" },
    { label: "Pass Rate", value: "92%", trend: "+4.3%" },
    { label: "Course Completion", value: "78%", trend: "+1.2%" },
  ],
  teachers: [
    {
      id: 1,
      name: "Dr. Sarah Johnson",
      department: "Computer Science",
      expertise: "Machine Learning",
      experience: "12 years",
      email: "sarah.j@university.edu",
      phone: "+1234567890",
      image:
        "https://images.unsplash.com/photo-1736281547025-46a511438ee0?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwxMnx8fGVufDB8fHx8fA%3D%3D",
      availability: ["Morning", "Afternoon"],
    },
    {
      id: 2,
      name: "Prof. Michael Chen",
      department: "Computer Science",
      expertise: "Database Systems",
      experience: "15 years",
      email: "michael.c@university.edu",
      phone: "+1234567891",
      image:
        "https://images.unsplash.com/photo-1736148391814-1734e7acf55c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4MHx8fGVufDB8fHx8fA%3D%3D",
      availability: ["Morning"],
    },
    {
      id: 3,
      name: "Dr. Emily Brown",
      department: "Computer Science",
      expertise: "Software Engineering",
      experience: "8 years",
      email: "emily.b@university.edu",
      phone: "+1234567892",
      image:
        "https://images.unsplash.com/photo-1736148662656-83a390775f32?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0M3x8fGVufDB8fHx8fA%3D%3D",
      availability: ["Afternoon"],
    },
    {
      id: 4,
      name: "Dr. David Lee",
      department: "Computer Science",
      expertise: "Artificial Intelligence",
      experience: "10 years",
      email: "david.l@university.edu",
      phone: "+1234567893",
      image:
        "https://images.unsplash.com/photo-1735977161893-d969d37f32c5?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2Nnx8fGVufDB8fHx8fA%3D%3D",
      availability: ["Morning", "Afternoon"],
    },
    {
      id: 5,
      name: "Prof. Lisa Wang",
      department: "Computer Science",
      expertise: "Computer Networks",
      experience: "14 years",
      email: "lisa.w@university.edu",
      phone: "+1234567894",
      image:
        "https://images.unsplash.com/photo-1735380674308-9e278d784e8f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw3NHx8fGVufDB8fHx8fA%3D%3D",
      availability: ["Afternoon"],
    },
  ],
  courses: [
    {
      id: 1,
      name: "Advanced Database Systems",
      code: "CS401",
      semester: 4,
      credits: 4,
      enrolled: 120,
      teacher: "Prof. Michael Chen",
      progress: 75,
    },
    {
      id: 2,
      name: "Machine Learning Fundamentals",
      code: "CS402",
      semester: 4,
      credits: 4,
      enrolled: 95,
      teacher: "Dr. Sarah Johnson",
      progress: 65,
    },
    {
      id: 3,
      name: "Software Architecture",
      code: "CS403",
      semester: 4,
      credits: 3,
      enrolled: 85,
      teacher: "Dr. Emily Brown",
      progress: 80,
    },
    {
      id: 4,
      name: "Artificial Intelligence",
      code: "CS404",
      semester: 5,
      credits: 4,
      enrolled: 100,
      teacher: "Dr. David Lee",
      progress: 70,
    },
    {
      id: 5,
      name: "Computer Networks",
      code: "CS405",
      semester: 5,
      credits: 3,
      enrolled: 90,
      teacher: "Prof. Lisa Wang",
      progress: 60,
    },
  ],
  exams: [
    {
      id: 1,
      name: "Database Systems Mid-Term",
      course: "CS401",
      date: "2025-02-20",
      time: "09:00 AM",
      duration: "3 hours",
      rooms: ["Hall A", "Hall B"],
    },
    {
      id: 2,
      name: "Machine Learning Quiz",
      course: "CS402",
      date: "2025-02-22",
      time: "02:00 PM",
      duration: "1 hour",
      rooms: ["Lab 1", "Lab 2"],
    },
    {
      id: 3,
      name: "Software Architecture Final",
      course: "CS403",
      date: "2025-02-25",
      time: "10:00 AM",
      duration: "3 hours",
      rooms: ["Hall C"],
    },
    {
      id: 4,
      name: "Artificial Intelligence Mid-Term",
      course: "CS404",
      date: "2025-02-27",
      time: "11:00 AM",
      duration: "2 hours",
      rooms: ["Hall A", "Hall B"],
    },
    {
      id: 5,
      name: "Computer Networks Quiz",
      course: "CS405",
      date: "2025-03-01",
      time: "03:00 PM",
      duration: "1 hour",
      rooms: ["Lab 1", "Lab 2"],
    },
  ],
  rooms: [
    { id: "Hall A", capacity: 60, facilities: ["Projector", "AC", "CCTV"] },
    { id: "Hall B", capacity: 60, facilities: ["Projector", "AC", "CCTV"] },
    { id: "Lab 1", capacity: 30, facilities: ["Computers", "AC", "CCTV"] },
    { id: "Lab 2", capacity: 30, facilities: ["Computers", "AC", "CCTV"] },
    { id: "Hall C", capacity: 80, facilities: ["Projector", "AC", "CCTV"] },
  ],
  invigilators: [
    {
      id: 1,
      name: "Dr. Sarah Johnson",
      availability: ["Morning", "Afternoon"],
      assignedExams: [],
    },
    {
      id: 2,
      name: "Prof. Michael Chen",
      availability: ["Morning"],
      assignedExams: [],
    },
    {
      id: 3,
      name: "Dr. Emily Brown",
      availability: ["Afternoon"],
      assignedExams: [],
    },
    {
      id: 4,
      name: "Dr. David Lee",
      availability: ["Morning", "Afternoon"],
      assignedExams: [],
    },
    {
      id: 5,
      name: "Prof. Lisa Wang",
      availability: ["Afternoon"],
      assignedExams: [],
    },
  ],
};

